import $CastAndCrew from "./CastAndCrew";
import $Category from "./Category";
import $ComingSoon from "./ComingSoon";
import $FilmGrid from "./FilmGrid";
import $Filmography from "./Filmography";
import $Films from "./Films";
import $Genres from "./Genres";
import $Header from "./Header";
import $Navigation from "./Navigation";
import $NowPlaying from "./NowPlaying";
import $People from "./People";
import $Poster from "./Poster";
import $Recommendations from "./Recommendations";
import $Search from "./Search";

export const CastAndCrew = $CastAndCrew;
export const Category = $Category;
export const ComingSoon = $ComingSoon;
export const FilmGrid = $FilmGrid;
export const Filmography = $Filmography;
export const Films = $Films;
export const Genres = $Genres;
export const Header = $Header;
export const Navigation = $Navigation;
export const NowPlaying = $NowPlaying;
export const People = $People;
export const Poster = $Poster;
export const Recommendations = $Recommendations;
export const Search = $Search;